/**
 * lib/canonical/data.ts
 *
 * GENERATED FILE — do not edit by hand.
 * Regenerate with:
 *   node scripts/build-canonical-data.mjs <path to emailMapping.xlsx>
 *
 * Source: emailMapping.xlsx (Client and Supplier sheets), the mapping the
 * operations mailbox already uses to attribute inbound email. Standardising
 * uploads against the same list keeps the tracker and the mailbox in step.
 */

/** Canonical client names (38). */
export const CANONICAL_CLIENTS: readonly string[] = [
  "Action Drill and Blast",
  "Adapt",
  "AES",
  "Airmaster Corporation",
  "Blue Lake Milling",
  "Camco Engineering",
  "CBH Group",
  "Develop",
  "DIAB",
  "Elliot Insurance",
  "energy power systems",
  "Fredon Industries Pty Ltd",
  "galactic",
  "Golding",
  "Hort Enterprises Pty Ltd",
  "LCS Landscapes",
  "Lithium Australia Limited",
  "livium",
  "Magellan Power",
  "MEC Global - Bourke",
  "MEC Global - Collins",
  "MEC Global - Pitt",
  "Megasorber",
  "North Metropolitan Tafe",
  "nrw",
  "NRW Civil & Mining",
  "NRW Holdings",
  "OFI Group",
  "Optimum Air",
  "Primero",
  "RCR",
  "Sadleirs Transport Co Pty Ltd",
  "SASHVets",
  "schools",
  "St James Anglican School",
  "stoddart",
  "tammy",
  "Total AMS",
];

/** Canonical supplier names (85). */
export const CANONICAL_SUPPLIERS: readonly string[] = [
  "Actew AGL",
  "Activewest",
  "Agas National",
  "AGL",
  "Air Liquid",
  "Alinta",
  "Ampol",
  "Atom",
  "Aura",
  "Aurora Energy",
  "Ausgrid",
  "Axia Corporate Property",
  "Bap Cor",
  "BFcards",
  "Blackwoods",
  "BOC",
  "BP",
  "Castrol",
  "Chevron",
  "CitiPower & Powercor",
  "City & Regional Fuels",
  "Cleanaway",
  "Coregas",
  "Custom Fleet",
  "Cygnet West",
  "DM3",
  "Dunnings",
  "Elgas",
  "Energy Australia",
  "Energy Resources",
  "Energy Tec",
  "Engie",
  "Ergon",
  "Exmouth Fuel Supplies",
  "Flow Power",
  "Forkwest",
  "Fremantle Ports",
  "Fuchs",
  "Genesis Energy",
  "Greater Western Water",
  "GSFS",
  "Horizon",
  "ILD Direct",
  "Instant Waste",
  "Jandakot Refuelling Services",
  "JJL",
  "JLL",
  "Liberty Oil",
  "Locality Energy",
  "Mercury",
  "Midwest Ports",
  "Mini Tankers",
  "Mogas Regional",
  "Momentum",
  "Napa Parts",
  "Oil and Energy",
  "Origin",
  "Orix",
  "Perth Airport",
  "PKTR Energy",
  "Recharge Petroleum",
  "Red Energy",
  "Refuel AUS",
  "Shell",
  "Southern Ports",
  "Speedie Waste",
  "Statewide Oil",
  "Summit Fleet",
  "Supagas",
  "Superior Waste",
  "Sydney Water",
  "Synergy",
  "Tango Energy",
  "Tasco Petroleum",
  "TFAL",
  "Toyota Fleet",
  "Urbus Property",
  "Valvoline Global",
  "Veolia",
  "Viva Energy",
  "WA Fuels",
  "Water Corporation",
  "Western Power",
  "Wex Australia",
  "Win Connect",
];

/** Sender email domain → canonical supplier name (108). */
export const SUPPLIER_DOMAINS: Readonly<Record<string, string>> = {
  "actewagl.com.au": "Actew AGL",
  "activewestre.com.au": "Activewest",
  "agasnational.com.au": "Agas National",
  "agl.com.au": "AGL",
  "aglconnections.agl.com.au": "AGL",
  "airliquide.com": "Air Liquid",
  "alintaenergy.com.au": "Alinta",
  "ampol.com.au": "Ampol",
  "anz.veolia.com": "Veolia",
  "atom.com.au": "Atom",
  "aurapropertysc.com.au": "Aura",
  "auroraenergy.com.au": "Aurora Energy",
  "ausgrid.com.au": "Ausgrid",
  "axiacp.com.au": "Axia Corporate Property",
  "bapcor.com": "Bap Cor",
  "bfcards.com.au": "BFcards",
  "bigpond.com": "Exmouth Fuel Supplies",
  "blackwoods.com.au": "Blackwoods",
  "boc.com": "BOC",
  "bp.com": "BP",
  "businessenergy.synergy.net.au": "Synergy",
  "cardreports.ampol.com.au": "Ampol",
  "castrol.com.au": "Castrol",
  "chevron.com": "Chevron",
  "cleanaway.com.au": "Cleanaway",
  "communications.vivaenergy.com.au": "Viva Energy",
  "coregas.com": "Coregas",
  "coregas.com.au": "Coregas",
  "crfuels.com.au": "City & Regional Fuels",
  "customfleet.com.au": "Custom Fleet",
  "cygnetwest.com": "Cygnet West",
  "dm3.com.au": "DM3",
  "dunningsfuel.com.au": "Dunnings",
  "elgas.com.au": "Elgas",
  "email.powercor.com.au": "CitiPower & Powercor",
  "email.vivaenergy.com.au": "Viva Energy",
  "energy.agl.com.au": "AGL",
  "energyaustralia.com.au": "Energy Australia",
  "energyaustraliaonline.com.au": "Energy Australia",
  "energyresources.com.au": "Energy Resources",
  "energytec.com.au": "Energy Tec",
  "engie.com": "Engie",
  "ergon.com.au": "Ergon",
  "flowpower.com.au": "Flow Power",
  "forkwest.com.au": "Forkwest",
  "fremantleports.com.au": "Fremantle Ports",
  "fuchs.com": "Fuchs",
  "genesisenergy.co.nz": "Genesis Energy",
  "gsfs.com.au": "GSFS",
  "gww.com.au": "Greater Western Water",
  "horizonpower-reply.com.au": "Horizon",
  "horizonpower.com.au": "Horizon",
  "hydro.com.au": "Momentum",
  "ilddirect.com": "ILD Direct",
  "ildgroup.com.au": "ILD Direct",
  "instantwaste.com.au": "Instant Waste",
  "jandakotrefuellingservices.com.au": "Jandakot Refuelling Services",
  "jjl.com": "JJL",
  "jll.com": "JLL",
  "libertyoil.com.au": "Liberty Oil",
  "localityenergy.com.au": "Locality Energy",
  "mail.horizonpower.com.au": "Horizon",
  "mercury.co.nz": "Mercury",
  "midwestports.com.au": "Midwest Ports",
  "mogasregional.com.au": "Mogas Regional",
  "momentum.com.au": "Momentum",
  "napaparts.com.au": "Napa Parts",
  "notice.auroraenergy.com.au": "Aurora Energy",
  "oilandenergy.com.au": "Oil and Energy",
  "online.boc.com": "BOC",
  "origin.com.au": "Origin",
  "originenergy.com.au": "Origin",
  "orix.com.au": "Orix",
  "otr.com.au": "Mogas Regional",
  "perthairport.com.au": "Perth Airport",
  "pktrenergy.com.au": "PKTR Energy",
  "powercor.com.au": "CitiPower & Powercor",
  "rechargepetroleum.com.au": "Recharge Petroleum",
  "redenergy.com.au": "Red Energy",
  "refuelaus.com.au": "Refuel AUS",
  "rfs.com.au": "Mini Tankers",
  "rka.net.au": "Oil and Energy",
  "shellenergy.com.au": "Shell",
  "southerncrosslubes.com.au": "Statewide Oil",
  "southernports.com.au": "Southern Ports",
  "speediewaste.com.au": "Speedie Waste",
  "statewideoil.com.au": "Statewide Oil",
  "summitfleet.com.au": "Summit Fleet",
  "supagas.com.au": "Supagas",
  "superiorwaste.com.au": "Superior Waste",
  "support.engie.com.au": "Engie",
  "support.ergonretail.com.au": "Ergon",
  "sydneywater.com.au": "Sydney Water",
  "synergy.net.au": "Synergy",
  "tangoenergy.com": "Tango Energy",
  "tascopetroleum.com.au": "Tasco Petroleum",
  "tfal.com.au": "TFAL",
  "toyota.com.au": "Toyota Fleet",
  "uk.bp.com": "BP",
  "urbusproperty.com.au": "Urbus Property",
  "valvolineglobal.com": "Valvoline Global",
  "veolia.com": "Veolia",
  "vivaenergy.com.au": "Viva Energy",
  "wafuels.com.au": "WA Fuels",
  "watercorporation.com.au": "Water Corporation",
  "westernpower.com.au": "Western Power",
  "wexaustralia.com": "Wex Australia",
  "winconnect.com.au": "Win Connect",
};
